fieldLayouts:
  0fb7a1e2-da23-40b8-95ba-78b6fe2379d6:
    tabs:
      -
        elements:
          -
            fieldUid: 76099428-f3d4-42a7-9bb8-08f425b41461
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b9d7836-9646-42ac-b0ad-9c84e67a71d2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e0ee7443-387e-4be3-a64f-3c5ae52be354
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54daa4d7-b5cf-4458-9e19-67155be19343
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Organisational Information'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1a4aeb91-9082-4e96-abd7-5d5b470653c6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Partners
        sortOrder: 2
handle: organization
name: 'Organizational Information'
