fieldLayouts:
  ae81ae30-d804-4ab6-ae3c-069c5f405e09:
    tabs:
      -
        elements:
          -
            fieldUid: 78023dfa-3c9e-47d1-bedc-b6fa76c9d751
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: df090dc9-1e25-4504-abd3-18e7996d8d6d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d39b90d3-13a8-4d42-b415-1ef20426a174
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 11916eb5-92ff-4945-bb06-1406d6047b36
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: d08d0466-34f4-441b-acd1-439b514f3810
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 07ebbed0-759a-4198-8667-d238f87b8af1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Placeholder Images'
        sortOrder: 1
handle: placeholders
name: Placeholders
