fieldLayouts:
  f716694b-59bd-45c1-8caf-8ac5f5c29dcb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 648e7555-63ed-4228-a6b7-7811c865a7af
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: faqCategories
name: 'FAQ Categories'
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54:
    hasUrls: true
    template: ''
    uriFormat: 'faq-categories/{slug}'
structure:
  maxLevels: null
  uid: 0a08a1e9-aa08-457b-8f9c-a164104c23a5
