fieldLayouts:
  b186400c-9903-466b-9d3f-5776c8e41f53:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Cover Image Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: 'Cover Image Metadata'
        sortOrder: 1
handle: covers
hasUrls: true
name: 'Cover Photos'
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: $CLOUDFRONT_PATH_PREFIX
  expires: '3 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: '1'
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: coverphotos/
sortOrder: 6
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
