fieldLayouts:
  d71f5c60-3cff-4cd2-8a9f-e9ddab6681f4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 870c07d7-9341-4f1f-825b-25c76239bc0d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c198fd4c-43a4-41e6-b32f-fd21ac7db488
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Image Optimisation'
        sortOrder: 2
handle: heroImages
hasUrls: true
name: 'Hero Images'
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: ''
  expires: '3 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: '1'
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: heroes/
sortOrder: 8
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
