fieldLayouts:
  075e5de5-1534-48c8-8e78-abd4368bb026:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 66f529da-276b-4a1d-acb2-fa31dca6ebfc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: openGraphImages
hasUrls: true
name: 'Open Graph Images'
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $S3_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: $CLOUDFRONT_PATH_PREFIX
  expires: '3 months'
  keyId: $S3_KEY_ID
  makeUploadsPublic: '1'
  region: $S3_REGION
  secret: $S3_SECRET
  storageClass: ''
  subfolder: opengraph/
sortOrder: 10
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
