field: 8f760830-6b64-449f-98d0-c8139dda7403
fieldLayouts:
  e0aa25fa-40f5-4235-b469-6d940ff98c38:
    tabs:
      -
        elements:
          -
            fieldUid: ddf7329e-05b7-4282-8bf7-d129a53a5e97
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ddf7329e-05b7-4282-8bf7-d129a53a5e97:
    contentColumnType: text
    fieldGroup: null
    handle: article
    instructions: 'Enter one more paragraphs to create your textual content.'
    name: 'Body Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Content.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: article
name: 'Article Body'
sortOrder: 2
