field: 8f760830-6b64-449f-98d0-c8139dda7403
fieldLayouts:
  8a6b328b-5eb0-4059-ab39-ce5155345430:
    tabs:
      -
        elements:
          -
            fieldUid: 6010a80a-ff70-459e-9e0d-f2ae9076d1d3
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6010a80a-ff70-459e-9e0d-f2ae9076d1d3:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Select images that you want to display as a grid on the page, maximum 8 images allowed.'
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5'
      defaultUploadLocationSubpath: ''
      limit: '8'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add images'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: galleryImages
name: 'Tiled Gallery'
sortOrder: 6
