field: 373956bd-ab65-407b-a558-6a67fb1f74f4
fieldLayouts:
  f63426cb-44f3-4c90-9fd4-499a36acca60:
    tabs:
      -
        elements:
          -
            fieldUid: 54b0b75f-de71-41a4-a92c-b7d89cc44338
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2101ba21-d701-4fcd-9634-ac7a0868039d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c82cb2b0-4963-4031-86c0-52212d19670a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: fc774089-a868-4761-8651-ff8336d45a72
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  2101ba21-d701-4fcd-9634-ac7a0868039d:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'A short introductory paragraph that summaries the page.'
    name: Standfirst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  54b0b75f-de71-41a4-a92c-b7d89cc44338:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'A short and succinct heading'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c82cb2b0-4963-4031-86c0-52212d19670a:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:98a5c9ce-dbf3-469a-8dec-eac422e9040f'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fc774089-a868-4761-8651-ff8336d45a72:
    contentColumnType: text
    fieldGroup: null
    handle: colorPalette
    instructions: 'Set a theme colour for the page'
    name: 'Page Colour'
    searchable: false
    settings:
      palette: Default
      useConfigFile: '1'
    translationKeyFormat: null
    translationMethod: none
    type: percipioglobal\colourswatches\fields\ColourSwatches
handle: heroContent
name: 'Content Header'
sortOrder: 2
