field: 1266c39b-94f2-433c-ac8e-e84aa225a740
fieldLayouts:
  a73e2e27-cf9a-4425-b353-3b16b7b96869:
    tabs:
      -
        elements:
          -
            fieldUid: 6843ef52-9bcd-483a-956a-b63193181c85
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21df72f8-6b89-4f91-9c09-d04a531f29de
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f1db3ebb-c604-4fa8-9f2d-4255e0515ea9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  21df72f8-6b89-4f91-9c09-d04a531f29de:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Add an additional description to the page'
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6843ef52-9bcd-483a-956a-b63193181c85:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Use this if you want a custom title different from the entry title. If you don''t fill in this field, the entry title will be used'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f1db3ebb-c604-4fa8-9f2d-4255e0515ea9:
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: 'Create call to action to other pages'
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - aa00fbfa-4274-4def-a5e0-651e06d5baae
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_12_buttons}}'
      fieldLayout: table
      maxRows: '2'
      minRows: '0'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: heroContent
name: 'Hero Content'
sortOrder: 2
