field: 1266c39b-94f2-433c-ac8e-e84aa225a740
fieldLayouts:
  b0372d69-c68d-49a1-bf2e-7079cfe035dd:
    tabs:
      -
        elements:
          -
            fieldUid: ea74ba6b-b787-414c-9f83-a01b8377bd73
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 040d9f96-b22c-414c-8b92-9ec41f548a81
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af937c7b-a59e-445e-ac72-b9c36b9854f0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  040d9f96-b22c-414c-8b92-9ec41f548a81:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Add an additional description to the page'
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  af937c7b-a59e-445e-ac72-b9c36b9854f0:
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: 'Create call to action to other pages'
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 68e8bef5-3752-4c83-a67b-6fe5d31c976a
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_buttons}}'
      fieldLayout: row
      maxRows: '2'
      minRows: '0'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  ea74ba6b-b787-414c-9f83-a01b8377bd73:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Use this if you want a custom title different from the entry title. If you don''t fill in this field, the entry title will be used'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heroMain
name: 'Hero Image'
sortOrder: 1
