field: 8f760830-6b64-449f-98d0-c8139dda7403
fieldLayouts:
  62d8b20e-eea8-40fb-99a3-15f3f842d0b0:
    tabs:
      -
        elements:
          -
            fieldUid: eeffe250-cc99-427a-8259-4d32c52b9973
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  eeffe250-cc99-427a-8259-4d32c52b9973:
    contentColumnType: string
    fieldGroup: null
    handle: resources
    instructions: ''
    name: Resources
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - ca199daf-c114-4b71-bba9-c72951a2a6ae
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f121272f-9092-42a5-8c29-81292641be4d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 84c985c4-ffa3-4ff0-8e3b-4cdf2c5eba4c
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_13_resources}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: resourceList
name: 'Resource List'
sortOrder: 7
