field: 8f760830-6b64-449f-98d0-c8139dda7403
fieldLayouts:
  93168b10-fbdb-4072-99bf-d1ac2e7ea649:
    tabs:
      -
        elements:
          -
            fieldUid: 2c70f208-672c-4382-857b-e26634e13708
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 520c9b79-f508-44d3-ba3e-d3d4d8358648
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 49a29ae2-e9c2-44bb-9ede-4b304e587469
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c233f4c-6127-421c-a9e8-265f04666ff1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1c233f4c-6127-421c-a9e8-265f04666ff1:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Enter an optional caption for the image, if an image already contains a caption in it''s metadata, adding a caption here field will override the one embedded in the image.'
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2c70f208-672c-4382-857b-e26634e13708:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Select or upload an image to use in the page.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  49a29ae2-e9c2-44bb-9ede-4b304e587469:
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: 'Select the Aspect Ratio where you want the image to be displayed in, use live preview to see how it looks.'
    name: Ratio
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '1:1'
            -
              - value
              - is1by1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2:1'
            -
              - value
              - is2by1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - is4by3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3:4'
            -
              - value
              - is3by4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '7:5'
            -
              - value
              - is7by5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '8:5'
            -
              - value
              - is8by5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - is16by9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '21:9'
            -
              - value
              - is21by9
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  520c9b79-f508-44d3-ba3e-d3d4d8358648:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'Select a position where you want the image to be displayed, if you select left or right it will display next to the text. If you want multiple images in the same row, please select tiled gallery.'
    name: Position
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - '1'
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
handle: singleImage
name: Image
sortOrder: 5
