contentColumnType: text
fieldGroup: 0dd08fc1-c043-49cb-bdcf-80521b7bd98a
handle: colorPalette
instructions: 'Chose the colour palette you''d like to use throughout this page'
name: 'Page Colour Palette'
searchable: false
settings:
  palette: Default
  useConfigFile: '1'
translationKeyFormat: null
translationMethod: none
type: percipioglobal\colourswatches\fields\ColourSwatches
