contentColumnType: string(640)
fieldGroup: b2330e68-6c4a-45ab-b5b1-8a510f75ce4f
handle: description
instructions: 'Used both in Google search results and when this page is shared on social media sites'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: '1'
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
