contentColumnType: string
fieldGroup: 07a123c0-4e8e-4c19-a79e-61829f5d88c0
handle: heroBuilder
instructions: 'Use this field to set the page header. '
name: 'Page Header'
searchable: false
settings:
  contentTable: '{{%matrixcontent_herobuilder}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
