contentColumnType: string
fieldGroup: b2330e68-6c4a-45ab-b5b1-8a510f75ce4f
handle: newsCategory
instructions: 'Please select or create a category this entry belongs to.'
name: 'News Category'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:f326369d-c220-40d9-92e9-7b7b7811d8e5'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
