contentColumnType: text
fieldGroup: 1572f461-2a67-47a4-a36c-80839168bcb7
handle: organizationPhone
instructions: 'Enter your organization''s phone number'
name: 'Organization Phone'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
