contentColumnType: text
fieldGroup: 1572f461-2a67-47a4-a36c-80839168bcb7
handle: organizationInfo
instructions: 'Enter the organisations info that displays at the bottom of the website'
name: 'Organization Info'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
