contentColumnType: string
fieldGroup: 0314e405-e731-462f-9381-2cfb6ac91134
handle: pageImage
instructions: ''
name: 'Page Image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'Add a page image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:98a5c9ce-dbf3-469a-8dec-eac422e9040f'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:98a5c9ce-dbf3-469a-8dec-eac422e9040f'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
