contentColumnType: string
fieldGroup: 1572f461-2a67-47a4-a36c-80839168bcb7
handle: partners
instructions: 'Add and select a partner logo to upload and display in the footer'
name: Partners
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 73130918-5137-4525-ae1a-fbe8881589fd
        -
          __assoc__:
            -
              - width
              - 25%
      -
        - d5797faa-ba66-4ce3-b252-506ea5b41fc9
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 82093ae2-8665-438a-aaf9-e40fc7233840
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_partners}}'
  fieldLayout: table
  maxRows: '6'
  minRows: '1'
  propagationMethod: all
  selectionLabel: 'Add a partner'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
