contentColumnType: string(640)
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99
handle: standfirst
instructions: 'A short introductory paragraph in an article that summaries the page / article.'
name: Standfirst
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
