field: 1a4aeb91-9082-4e96-abd7-5d5b470653c6
fieldLayouts:
  f4021b7c-ee58-4e83-8e0c-f5d3f7557ad3:
    tabs:
      -
        fields:
          73130918-5137-4525-ae1a-fbe8881589fd:
            required: '1'
            sortOrder: '0'
          82093ae2-8665-438a-aaf9-e40fc7233840:
            required: '1'
            sortOrder: '2'
          d5797faa-ba66-4ce3-b252-506ea5b41fc9:
            required: '1'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  73130918-5137-4525-ae1a-fbe8881589fd:
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: 'Upload a partner logo as SVG'
    name: Logo
    searchable: '1'
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Add a partner logo'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  82093ae2-8665-438a-aaf9-e40fc7233840:
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: ''
    name: 'Website URL'
    searchable: '1'
    settings:
      allowCustomText: false
      allowTarget: false
      autoNoReferrer: false
      defaultLinkName: url
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  d5797faa-ba66-4ce3-b252-506ea5b41fc9:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Name
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
