field: f1db3ebb-c604-4fa8-9f2d-4255e0515ea9
fieldLayouts:
  398ed9cb-50a9-459a-9460-3b0c76d5aa4d:
    tabs:
      -
        elements:
          -
            fieldUid: aa00fbfa-4274-4def-a5e0-651e06d5baae
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  aa00fbfa-4274-4def-a5e0-651e06d5baae:
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: 'Select and entry you want to refer to'
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        __assoc__:
          -
            - url
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - custom
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - email
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - tel
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - asset
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - enabled
                  - true
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - site
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - sites
                  - '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
