field: eeffe250-cc99-427a-8259-4d32c52b9973
fieldLayouts:
  abec1223-d5e9-4aeb-a565-ad54997284f9:
    tabs:
      -
        elements:
          -
            fieldUid: ca199daf-c114-4b71-bba9-c72951a2a6ae
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f121272f-9092-42a5-8c29-81292641be4d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84c985c4-ffa3-4ff0-8e3b-4cdf2c5eba4c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  84c985c4-ffa3-4ff0-8e3b-4cdf2c5eba4c:
    contentColumnType: string
    fieldGroup: null
    handle: resource
    instructions: 'Upload or select your file'
    name: Resource
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - compressed
        - excel
        - pdf
        - powerpoint
        - text
        - word
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add a resource'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:b011a3f9-88a2-4819-aad0-ca04487dfac8'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ca199daf-c114-4b71-bba9-c72951a2a6ae:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'Enter your label for the resource file'
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f121272f-9092-42a5-8c29-81292641be4d:
    contentColumnType: string
    fieldGroup: null
    handle: utilityIcon
    instructions: 'Choose the icon you want to display File Icon will show the icon of the File Type being uploaded'
    name: 'Utility Icon'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'File Icon'
            -
              - value
              - fileIcon
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Download
            -
              - value
              - 'far fa-download-cloud-alt'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
