fieldLayouts:
  35854d6f-8d37-49c3-b4ef-fb284ccdefa7:
    tabs:
      -
        elements:
          -
            fieldUid: 9f9f4c61-0fb7-4139-a502-f16ad5a28a98
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: 'Enter the question'
            label: Question
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: c5eb6385-f146-4eb3-ac36-524ad29a1045
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: FAQ
        sortOrder: 1
handle: faqs
hasTitleField: true
name: FAQ
section: 77caab49-fa61-44b4-af86-3fa99cf8bace
sortOrder: 1
titleFormat: ''
