fieldLayouts:
  29456920-ac69-416e-9b72-d9e7baa46e32:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: 'The title of this landing page'
            label: 'Landing Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 373956bd-ab65-407b-a558-6a67fb1f74f4
            instructions: 'Complete the matrix below to populate the landing page header'
            label: 'Landing page hero'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f760830-6b64-449f-98d0-c8139dda7403
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Landing Page'
        sortOrder: 1
      -
        elements:
          -
            heading: 'SEO Metadata'
            type: craft\fieldlayoutelements\Heading
          -
            style: tip
            tip: 'By selecting a teaser image, you also ensure that this landing page is accompanied by an image when shared on social media sites'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 1c23eb9d-03fe-46ea-9bee-ff46e8bd15a3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a3feb81-50ce-467a-8aca-b5d4cc12aed0
            instructions: ''
            label: 'Meta Description'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d8b86c9-a2e1-4fb4-a836-76d1fecad043
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 2
      -
        elements:
          -
            heading: 'Page Settings'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: f388ed1e-62c6-4744-adba-cfe9737e3d50
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73d85143-6c77-4010-b0d1-07a316c0c120
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 3
handle: landingsPage
hasTitleField: true
name: 'Landing Page'
section: ef841ba4-7bcd-4ef5-9c12-96377bf7fba2
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
